### ISSUE TITLE
使用https链接显示此链接非私人连接，我无法使用

### ISSUE THREAD

**Issue by jonnyq** [hjmmc/WebGyroForCemuhook#11]
使用https链接显示此链接非私人连接，我无法使用，不知道是SSL证书问题还是怎么回事。

**Comment by hjmmc** [comment]
证书会自动更新的，请检查系统时间和URL

URL请输入 https://192-168-1-111.xip.lhjmmc.cn:8443

ip之间用 - 分隔，保证域名是 *.xip.lhjmmc.cn 的形式

**Comment by hjmmc** [comment]
![IMG_0695](https://user-images.githubusercontent.com/12729036/75123971-f4568880-56e6-11ea-93ae-70f0278c3550.PNG)

**Comment by BlackieKing** [comment]
![image](https://user-images.githubusercontent.com/27262203/75623639-ea50f000-5be6-11ea-985e-df3205f3fff8.png)
大佬，,我也遇到了同样的问题，之前我记得是能打开的，但是现在不行了，IOS13.3.1，https访问

**Comment by hjmmc** [comment]
证书不知道为啥被吊销了，已经重新生成了。
