### ISSUE TITLE
iOS 13.4 Don't Operate

### ISSUE THREAD

**Issue by BlackdeerY** [hjmmc/WebGyroForCemuhook#14]
iOS 13.4
Don't Operate.

**Permisson granted OK**, but Not Operate.
**(fullchain.pem profile installed)**

p.s.
cert.pem, fullchain.pem can be installed,
but key.pem are not.

**Comment by hjmmc** [comment]
Not need to install any pem, just use xip to visit the website.

When Permisson granted and x,y,z keep changing, you should test via PadTest.exe

**Comment by BlackdeerY** [comment]
Permission Granted,
but x0 y0 z0 No change and PadTest same.

I attach recorded gif.
allow permission > OK(not cancel) > ...
![RPReplay_Final1586602468-2](https://user-images.githubusercontent.com/49787913/79042005-08226380-7c2f-11ea-8387-389a6e378b79.gif)

**Comment by hjmmc** [comment]
It is estimated that the Webkit interface of ISO14 has changed, I will continue to follow up on this issue, thanks for the feedback

**Comment by hjmmc** [comment]
![7301886A-4BFE-40F1-BC9C-A66B0D2CAF69](https://user-images.githubusercontent.com/12729036/79202630-7a33bc00-7e6c-11ea-8915-07f250b4eb4b.png)

The DeviceMotionEvent.rotationRate return null. I has no idea the webkit api what's changed in ios 13.4 🤷‍♀️

**Comment by BlackdeerY** [comment]
Maybe there should be other people's feedback.
One thing is certain, neither my iPhone 8 nor iPad Pro 1 will work in iOS 13.4.
I turned off all antivirus and allowed 8443 inbound in the firewall, but it didn't work.

**Comment by BlackdeerY** [comment]
Have you find something?
I'm not Swift developer, and even have old Mac so I cannot download latest version of Xcode and check out.
I searched, but I couldn't find any articles about the bugs of other developers.
It should have worked on 13(13+ in UI), but I don't know when it return null.

https://developer.apple.com/documentation/webkitjs/devicemotionevent/1634377-rotationrate
- This property is null if the device cannot provide the rate of rotation ..?? ;(
(All iPhone have a gyroscope, so there may be a permission problem)

**Comment by BlackdeerY** [comment]
Have you find something?
I'm not Swift developer, and even have old Mac so I cannot download latest version of Xcode and check out.
I searched, but I couldn't find any articles about the bugs of other developers.
It should have worked on 13(13+ in UI), but I don't know when it return null.

- https://developer.apple.com/documentation/webkitjs/devicemotionevent/1634377-rotationrate
This property is null if the device cannot provide the rate of rotation—that is, if the device does not have a gyroscope.
- https://developer.apple.com/documentation/webkitjs/devicemotionevent/1629483-acceleration
This property is null if the device cannot provide the user acceleration—that is, if the device does not have a gyroscope.
- https://developer.apple.com/documentation/webkitjs/devicemotionevent/1629110-accelerationincludinggravity
This property is never null because every Apple device has an accelerometer.

They say, All apple device have an accelerometer, but not a gyroscope.
Some of them have it.
I heard that all iPhone(4 or higher) have 3-axis gyro.
Hmm..........
(Maybe it's a permission issue)

**Comment by hjmmc** [comment]
The program  is running normally on ios13. But when I upgraded to ios13.4.1 in order to test this issue, rotationrate returned a null value. So, i don’t think  my device has no gyroscope.

**Comment by hjmmc** [comment]
The same [issues](https://github.com/aframevr/aframe/issues/4554)

Maybe it will be fixed by the next ios version. I said maybe. 😕

**Comment by samsgates** [comment]
same issue, is there any alternative solution?  until apple fix the IOS version

**Comment by BlackdeerY** [comment]
iOS 13.5 Update and it work properly.
