### ISSUE TITLE
iOS 12.2 - WebGyro stopped working

### ISSUE THREAD

**Issue by phantasm** [hjmmc/WebGyroForCemuhook#3]
After updating my iPhone to latest iOS 12.2, Gyro webpage stopped reading sensor values. Apple updated Mobile Safari with new privacy settings regarding sensor data, but I'm unable to fix the issue by enabling these new settings.

**Comment by hjmmc** [comment]
This is the same [issue.](https://github.com/aframevr/aframe/issues/3976)
I tried to enable Settings > Safari > Motion and Orientation access on my iPhoneXR(IOS12.2), but it doesn't seem to work.
I can't find a solution for now. Maybe you need an Android phone.

**Comment by anuoua** [comment]
@hjmmc hi, test with https, apple may disable motion on unsafe website.

**Comment by hjmmc** [comment]
> @hjmmc hi, test with https, apple may disable motion on unsafe website.

Thanks, it work for me.

**Comment by hjmmc** [comment]
> After updating my iPhone to latest iOS 12.2, Gyro webpage stopped reading sensor values. Apple updated Mobile Safari with new privacy settings regarding sensor data, but I'm unable to fix the issue by enabling these new settings.

Hey, I fix this issues. [gyro1.6_en.zip](https://github.com/hjmmc/WebGyroForCemuhook/releases/download/gyro1.6/gyro1.6_en.zip)
