### ISSUE TITLE
Gyro not working and throwing RangeErrors

### ISSUE THREAD

**Issue by krampfcookie** [hjmmc/WebGyroForCemuhook#4]
When having webgyro connected to cemu, and connecting my phone (Xs on 12.2) to the https server, it starts continously throwing out of range errors. Gyroscope data are not transfered over to cemu. Neither restarting my phone or pc worked. 
![image](https://user-images.githubusercontent.com/46372994/57980910-b29b0200-7a31-11e9-9b27-e9cf143c6f3c.png)

**Comment by hjmmc** [comment]
fixed

try [gyro1.7_en.zip](https://github.com/hjmmc/WebGyroForCemuhook/releases/download/gyro1.7/gyro1.7_en.zip)
