### ISSUE TITLE
The site won't load on https

### ISSUE THREAD

**Issue by ghost** [hjmmc/WebGyroForCemuhook#6]
It loads on http but not on https

I'm using iOS 12.2, and motion access for safari is on. I also tried chrome and it didn't work.

**Comment by hjmmc** [comment]
Can you open the HTTPS site on your computer by [https://localhost:8443](https://localhost:8443) ? show me some screenshots.

**Comment by ghost** [comment]
I tried: https://localhost:8443/

Chrome just said:
"This site can’t be reached localhost took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_TIMED_OUT"

**Comment by ghost** [comment]
I tried it again, for some reason the response was different.
https://localhost:8443/

Chrome did not want to open the link at first saying:
"Your connection is not private
Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

This server could not prove that it is localhost; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection."

But I clicked open anyway. Then the site would open. 


The other link still does not work on my phone though. 
![IMG_2534](https://user-images.githubusercontent.com/33064948/61191964-f3865e80-a6e2-11e9-8b8a-1b09ba5ba04f.PNG)

**Comment by hjmmc** [comment]
It seems that the HTTPS website is working properly, you need to trust the certificate to see the page content.

May be that your router's firewall or computer's firewall is blocking access to port 8443. Close your firewall and check again.

![20190715102149](https://user-images.githubusercontent.com/12729036/61192952-955d7980-a6ea-11e9-9be3-bbe9cf5ebc16.jpg)

**Comment by hjmmc** [comment]
Please check that the URL you entered is https://10.168.110.51:8443 instead of http://10.168.110.51:8443
