### ISSUE TITLE
"Motion and orientation access" gone from iOS 13 Safari settings

### ISSUE THREAD

**Issue by TrebuhD** [hjmmc/WebGyroForCemuhook#7]
Hi,

Nice app, but unfortunately I couldn't get it to work on iOS 13, because the motion access is not in the safari settings anymore. To make it work again, you'd need to add this snippet in your JS:

```javascript
window.DeviceMotionEvent.requestPermission()
.then(response => {
  if (response == 'granted') {
    // permission granted
  } else {
    // permission not granted
  }
})
```

(source: https://medium.com/@leemartin/three-things-im-excited-about-in-safari-13-994107ac6295)

**Comment by hjmmc** [comment]
Thank you for the information provided
