### ISSUE TITLE
Can't request permission to use gyroscope on ios 13+

### ISSUE THREAD

**Issue by TrongDo** [hjmmc/WebGyroForCemuhook#8]
When i pressed allow permission it keeps saying "permission not granted". Do you have any solutions? Thank you.
p/s: both safari and chrome do not work

**Comment by hjmmc** [comment]
Check 
1. Accessing using HTTPS（https://192-168-1-10.xip.lhjmmc.cn）
2. HTTPS certificates are secure
3. Restart safari and reclick allow button. (authorization window will pop up
)

**Comment by TrongDo** [comment]
Thank you. It works like a charm :)
I will close the issue.
